/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cgpa;

/**
 *
 * @author AZYSS
 */
public class SessionResultsPanel extends javax.swing.JPanel {

    /**
     * Creates new form SessionResultsPanel
     */
    public SessionResultsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sessionNameLabel = new javax.swing.JLabel();
        resultPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tcpLabel1 = new javax.swing.JLabel();
        tcpField1 = new javax.swing.JTextField();
        tnuLabel1 = new javax.swing.JLabel();
        tnuField1 = new javax.swing.JTextField();
        coField1 = new javax.swing.JTextField();
        mcField1 = new javax.swing.JTextField();
        tncField1 = new javax.swing.JTextField();
        gpaField1 = new javax.swing.JTextField();
        coLabel1 = new javax.swing.JLabel();
        mcLabel1 = new javax.swing.JLabel();
        tncLabel1 = new javax.swing.JLabel();
        gpaLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        tcpLabel2 = new javax.swing.JLabel();
        tcpField2 = new javax.swing.JTextField();
        tnuLabel2 = new javax.swing.JLabel();
        tnuField2 = new javax.swing.JTextField();
        coField2 = new javax.swing.JTextField();
        mcField2 = new javax.swing.JTextField();
        tncField2 = new javax.swing.JTextField();
        gpaField2 = new javax.swing.JTextField();
        coLabel2 = new javax.swing.JLabel();
        mcLabel2 = new javax.swing.JLabel();
        tncLabel2 = new javax.swing.JLabel();
        gpaLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        sessionGPALabel = new javax.swing.JLabel();
        sessionGPAField = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sessionNameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sessionNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sessionNameLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        add(sessionNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 370, 32));

        resultPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 204)));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "First Semester", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Harrington", 0, 12), new java.awt.Color(102, 102, 255))); // NOI18N

        tcpLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tcpLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tcpLabel1.setText("TCP =");
        tcpLabel1.setOpaque(true);

        tcpField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tcpField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tcpField1.setFocusable(false);

        tnuLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tnuLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tnuLabel1.setText("TNU =");
        tnuLabel1.setOpaque(true);

        tnuField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tnuField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tnuField1.setFocusable(false);

        coField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        coField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        coField1.setFocusable(false);

        mcField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mcField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        mcField1.setFocusable(false);

        tncField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tncField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tncField1.setFocusable(false);

        gpaField1.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        gpaField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        gpaField1.setFocusable(false);

        coLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        coLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        coLabel1.setText("C.O =");
        coLabel1.setOpaque(true);

        mcLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mcLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mcLabel1.setText("M.C =");
        mcLabel1.setOpaque(true);

        tncLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tncLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tncLabel1.setText("TNC =");
        tncLabel1.setOpaque(true);

        gpaLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        gpaLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        gpaLabel1.setText("GPA =");
        gpaLabel1.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(coLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tnuLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mcLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tcpLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tncLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(gpaLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gpaField1, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                    .addComponent(tcpField1)
                    .addComponent(tncField1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mcField1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(coField1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tnuField1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tcpLabel1)
                    .addComponent(tcpField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tnuLabel1)
                    .addComponent(tnuField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mcField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mcLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tncField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tncLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gpaField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gpaLabel1)))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Second Semester", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Harrington", 0, 12), new java.awt.Color(102, 102, 255))); // NOI18N

        tcpLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tcpLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tcpLabel2.setText("TCP =");
        tcpLabel2.setOpaque(true);

        tcpField2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tcpField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tcpField2.setFocusable(false);

        tnuLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tnuLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tnuLabel2.setText("TNU =");
        tnuLabel2.setOpaque(true);

        tnuField2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tnuField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tnuField2.setFocusable(false);

        coField2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        coField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        coField2.setFocusable(false);

        mcField2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mcField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        mcField2.setFocusable(false);

        tncField2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tncField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tncField2.setFocusable(false);

        gpaField2.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        gpaField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        gpaField2.setFocusable(false);

        coLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        coLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        coLabel2.setText("C.O =");
        coLabel2.setOpaque(true);

        mcLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mcLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mcLabel2.setText("M.C =");
        mcLabel2.setOpaque(true);

        tncLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tncLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tncLabel2.setText("TNC =");
        tncLabel2.setOpaque(true);

        gpaLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        gpaLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        gpaLabel2.setText("GPA =");
        gpaLabel2.setOpaque(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(coLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tnuLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mcLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tcpLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tncLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(gpaLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gpaField2, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                    .addComponent(tcpField2)
                    .addComponent(tncField2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mcField2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(coField2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tnuField2))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tcpLabel2)
                    .addComponent(tcpField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tnuLabel2)
                    .addComponent(tnuField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mcField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mcLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tncField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tncLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gpaField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gpaLabel2)))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        sessionGPALabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        sessionGPALabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        sessionGPALabel.setText("Session GPA = ");

        sessionGPAField.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        sessionGPAField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        sessionGPAField.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(sessionGPALabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sessionGPAField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sessionGPALabel, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(sessionGPAField))
                .addContainerGap())
        );

        javax.swing.GroupLayout resultPanelLayout = new javax.swing.GroupLayout(resultPanel);
        resultPanel.setLayout(resultPanelLayout);
        resultPanelLayout.setHorizontalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(resultPanelLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        resultPanelLayout.setVerticalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(resultPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField coField1;
    private javax.swing.JTextField coField2;
    private javax.swing.JLabel coLabel1;
    private javax.swing.JLabel coLabel2;
    private javax.swing.JTextField gpaField1;
    private javax.swing.JTextField gpaField2;
    private javax.swing.JLabel gpaLabel1;
    private javax.swing.JLabel gpaLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField mcField1;
    private javax.swing.JTextField mcField2;
    private javax.swing.JLabel mcLabel1;
    private javax.swing.JLabel mcLabel2;
    private javax.swing.JPanel resultPanel;
    private javax.swing.JTextField sessionGPAField;
    private javax.swing.JLabel sessionGPALabel;
    private javax.swing.JLabel sessionNameLabel;
    private javax.swing.JTextField tcpField1;
    private javax.swing.JTextField tcpField2;
    private javax.swing.JLabel tcpLabel1;
    private javax.swing.JLabel tcpLabel2;
    private javax.swing.JTextField tncField1;
    private javax.swing.JTextField tncField2;
    private javax.swing.JLabel tncLabel1;
    private javax.swing.JLabel tncLabel2;
    private javax.swing.JTextField tnuField1;
    private javax.swing.JTextField tnuField2;
    private javax.swing.JLabel tnuLabel1;
    private javax.swing.JLabel tnuLabel2;
    // End of variables declaration//GEN-END:variables

    
    void setTitle(String title){
        this.sessionNameLabel.setText(title);
    }
    
    void setSessionGPA(double gpa){
        this.sessionGPAField.setText(Double.toString(SemesterResultPanel.roundNumber(gpa, 1)));
    }
    
    void setSemesterTwoGPA(double gpa){
        this.gpaField2.setText(Double.toString(SemesterResultPanel.roundNumber(gpa, 1)));
    }
    
    void setSemesterOneGPA(double gpa){
        this.gpaField1.setText(Double.toString(SemesterResultPanel.roundNumber(gpa, 1)));
    }
    
    void setSemesterTwoTNC(int tnc){
        this.tncField2.setText(Integer.toString(tnc));
    }
    
    void setSemesterOneTNC(int tnc){
        this.tncField1.setText(Integer.toString(tnc));
    }
    
    void setSemesterTwoMC(int mc){
        this.mcField2.setText(Integer.toString(mc));
    }
    
    void setSemesterOneMC(int mc){
        this.mcField1.setText(Integer.toString(mc));
    }
    
    void setSemesterTwoCO(int co){
        this.coField2.setText(Integer.toString(co));
    }
    
    void setSemesterOneCO(int co){
        this.coField1.setText(Integer.toString(co));
    }
    
    void setSemesterTwoTNU(double tnu){
        this.tnuField2.setText(Integer.toString((int)tnu));
    }
    
    void setSemesterOneTNU(double tnu){
        this.tnuField1.setText(Integer.toString((int)tnu));
    }
    
    void setSemesterTwoTCP(double tcp){
        this.tcpField2.setText(Integer.toString((int)tcp));
    }
    
    void setSemesterOneTCP(double tcp){
        this.tcpField1 .setText(Integer.toString((int)tcp));
    }

}
